version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - zip -r ../nodejs-app.zip .
artifacts:
  files:
    - nodejs-app.zip
  discard-paths: yes
